# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    concurrency:
      group: ${{ github.workflow }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        id: build
        run: |
          yarn
          CI=false yarn build

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
        if: steps.build.conclusion == 'success'

  deploy:
    concurrency:
      group: ${{ github.workflow }}
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Deploy to thepeshka.github.io
        uses: tagus/git-deploy@v0.5.0
        with:
          changes: .
          repository: git@github.com:thepeshka/thepeshka.github.io.git
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: thepeshka
          email: ilya@thepeshka.ru
          message: https://github.com/thepeshka/me.thepeshka.ru/commit/${{ github.sha }}
          clean_repo: true
        if: steps.download-artifact.conclusion == 'success'

      - name: Deploy to thepeshka.ru
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
        if: steps.download-artifact.conclusion == 'success'
